// <auto-generated />
using System;
using Infra.Databases.SqlServers.UCondo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(UCondoContext))]
    partial class UCondoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AccountPlan.AccountPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AcceptLaunches")
                        .HasColumnType("bit");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptLaunches");

                    b.HasIndex("AccountType");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AccountPlan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab85bab5-45d8-4605-968a-dd330255f7db"),
                            AcceptLaunches = false,
                            AccountName = "Receitas",
                            AccountType = "Receita",
                            Code = "1"
                        },
                        new
                        {
                            Id = new Guid("1325ae6b-0906-4be8-a442-50cc0da01b1b"),
                            AcceptLaunches = true,
                            AccountName = "Rendimento de investimentos",
                            AccountType = "Receita",
                            Code = "5"
                        },
                        new
                        {
                            Id = new Guid("6c122240-52c9-48ce-bde6-a7de113cf0eb"),
                            AcceptLaunches = true,
                            AccountName = "Rendimento de investimentos",
                            AccountType = "Receita",
                            Code = "5.999"
                        },
                        new
                        {
                            Id = new Guid("41d61ea1-5bf6-46b5-b838-683624ab5d0e"),
                            AcceptLaunches = false,
                            AccountName = "Receitas",
                            AccountType = "Receita",
                            Code = "999"
                        },
                        new
                        {
                            Id = new Guid("2451444c-3e4a-4327-a67e-06f7e8dcc8d4"),
                            AcceptLaunches = false,
                            AccountName = "Receitas",
                            AccountType = "Receita",
                            Code = "999.999"
                        },
                        new
                        {
                            Id = new Guid("0912baaf-c96d-4c99-bdea-04fe8c1d4e55"),
                            AcceptLaunches = false,
                            AccountName = "Receitas",
                            AccountType = "Receita",
                            Code = "999.999.999"
                        },
                        new
                        {
                            Id = new Guid("519e761e-ae1a-4744-8e49-8883aace2592"),
                            AcceptLaunches = true,
                            AccountName = "Taxa condominial",
                            AccountType = "Receita",
                            Code = "1.1"
                        },
                        new
                        {
                            Id = new Guid("a8cc0cb5-9dc8-441f-8e50-8b923d369e48"),
                            AcceptLaunches = true,
                            AccountName = "Taxa condominial",
                            AccountType = "Receita",
                            Code = "1.2.999"
                        },
                        new
                        {
                            Id = new Guid("83653e46-e99a-415c-9554-434cc030f75a"),
                            AcceptLaunches = true,
                            AccountName = "Taxa condominial",
                            AccountType = "Receita",
                            Code = "1.999.999"
                        },
                        new
                        {
                            Id = new Guid("14bb1794-4b7b-4ca0-9971-1a8f3e138f1f"),
                            AcceptLaunches = true,
                            AccountName = "Reserva de dependência",
                            AccountType = "Receita",
                            Code = "1.2"
                        },
                        new
                        {
                            Id = new Guid("6db1fc3f-9197-4992-86bd-a97994f0e6dc"),
                            AcceptLaunches = true,
                            AccountName = "Multas",
                            AccountType = "Receita",
                            Code = "1.3"
                        },
                        new
                        {
                            Id = new Guid("76dce83c-baa9-4e8d-b7bb-f5824ae5aa70"),
                            AcceptLaunches = true,
                            AccountName = "Juros",
                            AccountType = "Receita",
                            Code = "1.4"
                        },
                        new
                        {
                            Id = new Guid("63fc0fcf-5753-4de6-ba12-d993a64ef363"),
                            AcceptLaunches = true,
                            AccountName = "Multa condominial",
                            AccountType = "Receita",
                            Code = "1.5"
                        },
                        new
                        {
                            Id = new Guid("2313b92d-f466-45aa-a290-f10d9cdde7a1"),
                            AcceptLaunches = true,
                            AccountName = "Água",
                            AccountType = "Receita",
                            Code = "1.6"
                        },
                        new
                        {
                            Id = new Guid("88872125-0fd6-48a0-bdf1-668ffc4162f8"),
                            AcceptLaunches = true,
                            AccountName = "Gás",
                            AccountType = "Receita",
                            Code = "1.7"
                        },
                        new
                        {
                            Id = new Guid("420c53f9-b468-485f-84df-6bd937987c40"),
                            AcceptLaunches = true,
                            AccountName = "Luz e energia",
                            AccountType = "Receita",
                            Code = "1.8"
                        },
                        new
                        {
                            Id = new Guid("c3527730-bf18-490e-a913-f5ef27d69735"),
                            AcceptLaunches = true,
                            AccountName = "Fundo de reserva",
                            AccountType = "Receita",
                            Code = "1.9"
                        },
                        new
                        {
                            Id = new Guid("0085fb9c-231d-4dd4-ae47-acef9746acf5"),
                            AcceptLaunches = true,
                            AccountName = "Fundo de obras",
                            AccountType = "Receita",
                            Code = "1.10"
                        },
                        new
                        {
                            Id = new Guid("0befd225-f57f-473d-8eb7-d3394fbc72a6"),
                            AcceptLaunches = true,
                            AccountName = "Correção monetária",
                            AccountType = "Receita",
                            Code = "1.11"
                        },
                        new
                        {
                            Id = new Guid("335aaf56-524f-413e-9678-d95bec2deeec"),
                            AcceptLaunches = true,
                            AccountName = "Transferência entre contas",
                            AccountType = "Receita",
                            Code = "1.12"
                        },
                        new
                        {
                            Id = new Guid("17d655e6-58d9-4aa9-ab00-270174e3e9fb"),
                            AcceptLaunches = true,
                            AccountName = "Pagamento duplicado",
                            AccountType = "Receita",
                            Code = "1.13"
                        },
                        new
                        {
                            Id = new Guid("e6e3ff32-971d-401c-a1d6-5325dc8e15f8"),
                            AcceptLaunches = true,
                            AccountName = "Cobrança",
                            AccountType = "Receita",
                            Code = "1.14"
                        },
                        new
                        {
                            Id = new Guid("97fd2834-b14d-4f7f-8439-53d1441283a3"),
                            AcceptLaunches = true,
                            AccountName = "Crédito",
                            AccountType = "Receita",
                            Code = "1.15"
                        },
                        new
                        {
                            Id = new Guid("4b8ae187-8375-4ec0-b3ca-1b6f87e852b9"),
                            AcceptLaunches = true,
                            AccountName = "Água mineral",
                            AccountType = "Receita",
                            Code = "1.16"
                        },
                        new
                        {
                            Id = new Guid("ab3fbef3-eeb8-4cef-8f9e-c014afbf2778"),
                            AcceptLaunches = true,
                            AccountName = "Estorno taxa de resgate",
                            AccountType = "Receita",
                            Code = "1.17"
                        },
                        new
                        {
                            Id = new Guid("43952b89-e4d2-4498-bd4b-47d4d117b771"),
                            AcceptLaunches = true,
                            AccountName = "Acordo",
                            AccountType = "Receita",
                            Code = "1.18"
                        },
                        new
                        {
                            Id = new Guid("7e5d8641-2aea-4683-985b-d49d0c8f0d31"),
                            AcceptLaunches = true,
                            AccountName = "Honorários",
                            AccountType = "Receita",
                            Code = "1.19"
                        },
                        new
                        {
                            Id = new Guid("dba8fae2-f7fe-478d-aa9a-ccb1f89e8776"),
                            AcceptLaunches = false,
                            AccountName = "Despesas",
                            AccountType = "Despesa",
                            Code = "2"
                        },
                        new
                        {
                            Id = new Guid("6667c738-a8e2-45a4-aa12-059d8152b7fe"),
                            AcceptLaunches = false,
                            AccountName = "Com pessoal",
                            AccountType = "Despesa",
                            Code = "2.1"
                        },
                        new
                        {
                            Id = new Guid("db67f854-e5f3-473e-9ab1-9a9531c5c88a"),
                            AcceptLaunches = true,
                            AccountName = "Salário",
                            AccountType = "Despesa",
                            Code = "2.1.1"
                        },
                        new
                        {
                            Id = new Guid("3dead6c1-f552-40d3-a3d7-e4d79a6e3c79"),
                            AcceptLaunches = true,
                            AccountName = "Adiantamento salarial",
                            AccountType = "Despesa",
                            Code = "2.1.2"
                        },
                        new
                        {
                            Id = new Guid("a01fcd20-6584-4f8d-8bcd-a96ea875d938"),
                            AcceptLaunches = true,
                            AccountName = "Hora extra",
                            AccountType = "Despesa",
                            Code = "2.1.3"
                        },
                        new
                        {
                            Id = new Guid("af576e9a-31f6-47da-87d5-8b839e3db04a"),
                            AcceptLaunches = true,
                            AccountName = "Férias",
                            AccountType = "Despesa",
                            Code = "2.1.4"
                        },
                        new
                        {
                            Id = new Guid("78f8236e-4054-42f8-b45c-aff84cc0c508"),
                            AcceptLaunches = true,
                            AccountName = "13º salário",
                            AccountType = "Despesa",
                            Code = "2.1.5"
                        },
                        new
                        {
                            Id = new Guid("c2d62a8b-152d-49ee-8369-240a7a71ba30"),
                            AcceptLaunches = true,
                            AccountName = "Adiantamento 13º salário",
                            AccountType = "Despesa",
                            Code = "2.1.6"
                        },
                        new
                        {
                            Id = new Guid("0bbf7a1f-9809-45b4-bb91-8f1e7a0a758b"),
                            AcceptLaunches = true,
                            AccountName = "Adicional de função",
                            AccountType = "Despesa",
                            Code = "2.1.7"
                        },
                        new
                        {
                            Id = new Guid("04d1cbec-3b2c-40af-ae11-a10f61992f6b"),
                            AcceptLaunches = true,
                            AccountName = "Aviso prévio",
                            AccountType = "Despesa",
                            Code = "2.1.8"
                        },
                        new
                        {
                            Id = new Guid("263fe42a-5778-4b37-bbc4-a331febec543"),
                            AcceptLaunches = true,
                            AccountName = "INSS",
                            AccountType = "Despesa",
                            Code = "2.1.9"
                        },
                        new
                        {
                            Id = new Guid("7cf0a687-d145-4ac1-87a4-93da09fa7898"),
                            AcceptLaunches = true,
                            AccountName = "FGTS",
                            AccountType = "Despesa",
                            Code = "2.1.10"
                        },
                        new
                        {
                            Id = new Guid("89216a8b-c04a-4c8b-baa0-6b36430e229b"),
                            AcceptLaunches = true,
                            AccountName = "PIS",
                            AccountType = "Despesa",
                            Code = "2.1.11"
                        },
                        new
                        {
                            Id = new Guid("97416bf0-41f0-4cd7-8a66-089ccbb6212c"),
                            AcceptLaunches = true,
                            AccountName = "Vale refeição",
                            AccountType = "Despesa",
                            Code = "2.1.12"
                        },
                        new
                        {
                            Id = new Guid("2b887533-a9a1-416c-850a-3d900cc06c5a"),
                            AcceptLaunches = true,
                            AccountName = "Vale transporte",
                            AccountType = "Despesa",
                            Code = "2.1.13"
                        },
                        new
                        {
                            Id = new Guid("198b5d55-0e9c-4166-bd90-413f383954a1"),
                            AcceptLaunches = true,
                            AccountName = "Cesta básica",
                            AccountType = "Despesa",
                            Code = "2.1.14"
                        },
                        new
                        {
                            Id = new Guid("0fc46cb9-10a7-476d-8b87-cf1b0cb147eb"),
                            AcceptLaunches = true,
                            AccountName = "Acordo trabalhista",
                            AccountType = "Despesa",
                            Code = "2.1.15"
                        },
                        new
                        {
                            Id = new Guid("9366370e-cd94-416a-96fe-3d7f90f3c876"),
                            AcceptLaunches = false,
                            AccountName = "Mensais",
                            AccountType = "Despesa",
                            Code = "2.2"
                        },
                        new
                        {
                            Id = new Guid("5905e325-646d-4de4-9384-79716057d7bf"),
                            AcceptLaunches = true,
                            AccountName = "Energia elétrica",
                            AccountType = "Despesa",
                            Code = "2.2.999"
                        },
                        new
                        {
                            Id = new Guid("c94de406-c331-4164-bdaf-2f72bb1a45fd"),
                            AcceptLaunches = true,
                            AccountName = "Água e esgoto",
                            AccountType = "Despesa",
                            Code = "2.2.2"
                        },
                        new
                        {
                            Id = new Guid("0dc2506d-d607-4cf0-b135-61a162cc28df"),
                            AcceptLaunches = true,
                            AccountName = "Taxa de administração",
                            AccountType = "Despesa",
                            Code = "2.2.3"
                        },
                        new
                        {
                            Id = new Guid("90795368-24c2-42c2-9d35-070af7788085"),
                            AcceptLaunches = true,
                            AccountName = "Gás",
                            AccountType = "Despesa",
                            Code = "2.2.4"
                        },
                        new
                        {
                            Id = new Guid("314e82af-4f44-4829-b781-8bc7ac12d41b"),
                            AcceptLaunches = true,
                            AccountName = "Seguro obrigatório",
                            AccountType = "Despesa",
                            Code = "2.2.5"
                        },
                        new
                        {
                            Id = new Guid("725f93cd-b584-480c-92f2-82135d395324"),
                            AcceptLaunches = true,
                            AccountName = "Telefone",
                            AccountType = "Despesa",
                            Code = "2.2.6"
                        },
                        new
                        {
                            Id = new Guid("ca5d22c0-88cf-40b0-9bb3-ab6c7f2666cb"),
                            AcceptLaunches = true,
                            AccountName = "Softwares e aplicativos",
                            AccountType = "Despesa",
                            Code = "2.2.7"
                        },
                        new
                        {
                            Id = new Guid("dc37db7f-4104-4d7c-93a0-4ef5cb53da56"),
                            AcceptLaunches = false,
                            AccountName = "Manutenção",
                            AccountType = "Despesa",
                            Code = "2.3"
                        },
                        new
                        {
                            Id = new Guid("e159aac6-ef27-47c1-92f2-007702c63fab"),
                            AcceptLaunches = true,
                            AccountName = "Elevador",
                            AccountType = "Despesa",
                            Code = "2.3.1"
                        },
                        new
                        {
                            Id = new Guid("f5987f3c-4cc3-499d-aae5-2b43780d6ca5"),
                            AcceptLaunches = true,
                            AccountName = "Limpeza e conservação",
                            AccountType = "Despesa",
                            Code = "2.3.2"
                        },
                        new
                        {
                            Id = new Guid("015e7216-5b47-4d06-b5ae-c7ad852e6450"),
                            AcceptLaunches = true,
                            AccountName = "Jardinagem",
                            AccountType = "Despesa",
                            Code = "2.3.3"
                        },
                        new
                        {
                            Id = new Guid("83aa9bb1-2a82-499f-a3ce-b759794a2a01"),
                            AcceptLaunches = false,
                            AccountName = "Diversas",
                            AccountType = "Despesa",
                            Code = "2.4"
                        },
                        new
                        {
                            Id = new Guid("e4e9f5ab-fefc-4d72-a4f9-24b7a98385f6"),
                            AcceptLaunches = true,
                            AccountName = "Honorários de advogado",
                            AccountType = "Despesa",
                            Code = "2.4.1"
                        },
                        new
                        {
                            Id = new Guid("7d2ffbcd-722d-43dd-8664-2247a0ede85c"),
                            AcceptLaunches = true,
                            AccountName = "Xerox",
                            AccountType = "Despesa",
                            Code = "2.4.2"
                        },
                        new
                        {
                            Id = new Guid("a05f9178-7efa-4efa-9d36-05788ae08789"),
                            AcceptLaunches = true,
                            AccountName = "Correios",
                            AccountType = "Despesa",
                            Code = "2.4.3"
                        },
                        new
                        {
                            Id = new Guid("aeff953a-d5c0-46de-be90-8573012ceaac"),
                            AcceptLaunches = true,
                            AccountName = "Despesas judiciais",
                            AccountType = "Despesa",
                            Code = "2.4.4"
                        },
                        new
                        {
                            Id = new Guid("37f1f8cd-ea84-45ac-9677-a43f1f69ee70"),
                            AcceptLaunches = true,
                            AccountName = "Multas",
                            AccountType = "Despesa",
                            Code = "2.4.5"
                        },
                        new
                        {
                            Id = new Guid("2a47fa3e-c806-4db9-b633-f2bc92980fba"),
                            AcceptLaunches = true,
                            AccountName = "Juros",
                            AccountType = "Despesa",
                            Code = "2.4.6"
                        },
                        new
                        {
                            Id = new Guid("ea1c7a72-66f4-478e-9e6d-6f96974981e0"),
                            AcceptLaunches = true,
                            AccountName = "Transferência entre contas",
                            AccountType = "Despesa",
                            Code = "2.4.7"
                        },
                        new
                        {
                            Id = new Guid("1356064b-a197-4cf0-9ac6-3b5106c42d6e"),
                            AcceptLaunches = false,
                            AccountName = "Despesas bancárias",
                            AccountType = "Despesa",
                            Code = "3"
                        },
                        new
                        {
                            Id = new Guid("d2a84a5e-1da3-45b6-8b4e-967d43ab258c"),
                            AcceptLaunches = true,
                            AccountName = "Registro de boletos",
                            AccountType = "Despesa",
                            Code = "3.1"
                        },
                        new
                        {
                            Id = new Guid("235edcfa-4104-48df-92ee-49304a3bb05c"),
                            AcceptLaunches = true,
                            AccountName = "Processamento de boletos",
                            AccountType = "Despesa",
                            Code = "3.2"
                        },
                        new
                        {
                            Id = new Guid("d2542ca5-d887-4976-aacb-ace1ca379cae"),
                            AcceptLaunches = true,
                            AccountName = "Registro e processamento de boletos",
                            AccountType = "Despesa",
                            Code = "3.3"
                        },
                        new
                        {
                            Id = new Guid("2273fd42-e8b4-4bc0-88b3-69d95850e325"),
                            AcceptLaunches = true,
                            AccountName = "Resgates",
                            AccountType = "Despesa",
                            Code = "3.4"
                        },
                        new
                        {
                            Id = new Guid("3de9397e-dfb8-48de-a6c3-e29b027a9fba"),
                            AcceptLaunches = false,
                            AccountName = "Outras receitas",
                            AccountType = "Receita",
                            Code = "4"
                        },
                        new
                        {
                            Id = new Guid("f0dda188-6f8f-4b8e-8a5f-41e60a7bf8c3"),
                            AcceptLaunches = true,
                            AccountName = "Rendimento de poupança",
                            AccountType = "Receita",
                            Code = "4.1"
                        },
                        new
                        {
                            Id = new Guid("9ae4b828-dc90-4ca6-a30b-f09b64e33551"),
                            AcceptLaunches = true,
                            AccountName = "Rendimento de investimentos",
                            AccountType = "Receita",
                            Code = "4.2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
